# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreKeeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='score',
            new_name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='total_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
