# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreKeeper', '0002_auto_20180327_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
